# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85a5cc5a87cd35ba4d45b6ece688eaccbdec79ff88af46c1cae10257fd43e49454772cda0f2ab049be3a5d925839493921e077df5d85a413721be1dd8ad08436

test:
  secret_key_base: 32d5a2b6e9a32194e2522701a29d322e9d4f31a8b2942e11f20c6abc70e3038bb4f0deca77a0e5f55fc518ec80bda3d2c0d99899577e4feb5d20eae27c1712a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
